/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Books": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CLOUDFRONT_KEY_PAIR_ID": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "CLOUDFRONT_PRIVATE_KEY": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "Translations": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}